import { useEffect, useState } from 'react';
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, Menu, X } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { Footer } from '@/components/ui';

export function PublicLayout() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const { user, isStaff, signOut } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll); }, []);
  useEffect(() => setMenuOpen(false), [location.pathname]);
  const nav = [{ label: 'Home', to: '/' }, { label: 'Events', to: '/events' }, { label: 'About', to: '/about' }, { label: 'Contact', to: '/contact' }];
  return <div className="min-h-screen bg-ivory"><header className={`fixed inset-x-0 top-0 z-40 transition-all duration-300 ${scrolled || location.pathname !== '/' ? 'bg-navy-950/95 shadow-lg backdrop-blur-xl' : 'bg-transparent'}`}><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-6 md:px-10"><Link to="/" className="flex items-center gap-3 text-white"><span className="grid h-9 w-9 place-items-center rounded-full border border-gold-300/70 font-display text-lg text-gold-200">P</span><div><p className="text-sm font-bold tracking-[0.2em]">PPSU EVENTS</p><p className="hidden text-[9px] uppercase tracking-[0.2em] text-white/45 sm:block">Experience more</p></div></Link><nav className="hidden items-center gap-8 md:flex">{nav.map((item) => <NavLink key={item.to} to={item.to} className={({ isActive }) => `text-sm transition ${isActive ? 'text-gold-200' : 'text-white/75 hover:text-white'}`}>{item.label}</NavLink>)}</nav><div className="hidden items-center gap-3 md:flex">{user ? <><Link to={isStaff ? '/admin' : '/dashboard'} className="rounded-full border border-white/20 px-4 py-2 text-sm text-white/80 hover:border-white/50 hover:text-white">{isStaff ? 'Admin portal' : 'My dashboard'}</Link><button onClick={() => { void signOut(); navigate('/'); }} className="btn-primary px-5 py-2.5">Sign out</button></> : <><Link to="/sign-in" className="px-4 py-2 text-sm text-white/80 hover:text-white">Sign in</Link><Link to="/events" className="btn-primary px-5 py-2.5">Get tickets <ArrowRight size={15} /></Link></>}</div><button aria-label="Open menu" onClick={() => setMenuOpen(true)} className="rounded-full border border-white/20 p-2 text-white md:hidden"><Menu size={20} /></button></div></header><AnimatePresence>{menuOpen && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 overflow-y-auto bg-navy-950 px-6 py-6 text-white"><div className="flex items-center justify-between"><Link onClick={() => setMenuOpen(false)} to="/" className="text-sm font-bold tracking-[0.2em]">PPSU EVENTS</Link><button aria-label="Close menu" onClick={() => setMenuOpen(false)} className="rounded-full border border-white/20 p-2"><X size={20} /></button></div><nav className="mt-20 space-y-7">{nav.map((item) => <NavLink key={item.to} to={item.to} className="block font-display text-4xl text-white/85">{item.label}</NavLink>)}<div className="mt-12 border-t border-white/10 pt-8">{user ? <Link className="btn-primary" to={isStaff ? '/admin' : '/dashboard'}>{isStaff ? 'Admin portal' : 'My dashboard'} <ArrowRight size={16} /></Link> : <div className="flex gap-3"><Link className="btn-primary" to="/sign-in">Sign in</Link><Link className="btn-outline" to="/events">Explore events</Link></div>}</div></nav></motion.div>}</AnimatePresence><main><Outlet /></main><Footer /></div>;
}
